export default [
  {
    id: 1,
    title: 'Gladiator',
    year: 2000,
    lang: 'English',
    director: 'Ridley Scott',
    stars: 'Russell Crowe',
    image: '/images/gladiator.jpg',
  },
  {
    id: 2,
    title: 'The Shawshank Redemption',
    year: 1994,
    lang: 'English',
    director: 'Frank Darabont',
    stars: 'Tim Robbins, Morgan Freeman',
    image: '/images/shawshankredemption.jpg',
  },
  {
    id: 3,
    title: 'Raya and the Last Dragon',
    year: 2021,
    lang: 'English',
    director: 'Don Hall',
    stars: 'Kelly Marie Tran, Awkwafina',
    image: '/images/raya.jpg',
  },
  {
    id: 4,
    title: 'The Godfather',
    year: 1972,
    lang: 'English',
    director: 'Francis Ford Coppola',
    stars: 'Marlon Brando, Al Pacino',
    image: '/images/godfather.jpg',
  },
  {
    id: 5,
    title: 'The Dark Knight',
    year: 2008,
    lang: 'English',
    director: 'Christopher Nolan',
    stars: 'Christian Bale, Heath Ledger',
    image: '/images/dark-knight.jpg',
  },
  {
    id: 6,
    title: 'Fight Club',
    year: 1999,
    lang: 'English',
    director: 'David Fincher',
    stars: 'Brad Pitt, Edward Norton',
    image: '/images/fight-club.jpg',
  },
];
